export const projects = [
  {
    name: "NASA",
    link: "https://nasa.tribaldeni.tech",
    git: "https://github.com/juicio8/nasa-project",
    image: "/project11.png",
    description:
      "A MERN stack project. Schedule, cancel and view nasa rocket launches. This was one of the projects done on a udemy course when learning nodejs. I implemented ci/cd pipelines with github actions, server-side tests with jest and supertest, containerized it with docker, and hosted it on aws ec2",
    tech: [
      "/css-icon.svg",
      "/javascript-programming-language-icon.svg",
      "/react-js-icon.svg",
    ],
    tech2: [
      "css",
      "javascript",
      "react",
      "nodejs",
      "mongodb",
      "jest",
      "supertest",
      "github actions",
      "docker",
      "aws",
    ],
  },
  {
    name: "Hollar",
    link: "https://www.youtube.com/watch?v=z7LnDOczLcg",
    git: "https://github.com/juicio8/Hollar",
    image: "/project12.png",
    description:
      "VERN stack. It's basically an idea, a social media app. I would love to use something like this to chat about recent movies/tvseries, view the trending movies and see what people are saying about it. I worked with vue, apollo, nodejs, mongodb. I used aggregate pipelines on mongodb, implemented authentication with bycrypt, login & signup with aws ses, profile udpate with aws s3. Unfortunately I've not hosted it yet, but you can watch a clip.",
    tech: [
      "/css-icon.svg",
      "/javascript-programming-language-icon.svg",
      "/react-js-icon.svg",
    ],
    tech2: [
      "css",
      "typescript",
      "vuejs",
      "nodejs",
      "mongodb",
      "apollo graphql",
      "github actions",
      "docker",
      "aws",
    ],
  },
  {
    name: "Ankaraworld catalog",
    link: "https://ankaraworldcatalog.netlify.app",
    git: "https://github.com/ankaraworld_catalog/",
    image: "/akc1.jpg",
    tech: [
      "/sb.svg",
      "/jest-js-icon.svg",
      "/typescript-programming-language-icon.svg",
      "/styled-components-1.svg",
      "/nextjs-icon.svg",
    ],
    tech2: [
      "styled-components",
      "typescript",
      "nextjs",
      "react",
      "jest",
      "storybook",
      "firebase",
    ],
    description:
      "Created a Catalog site while freelancing, I also built an admin site for ankara world to manage their products on the catalog site with firebase",
  },
  {
    name: "LoveMe App",
    link: "https://love-me.app",
    git: "https://github.com/workshopapps/loveletterwriter.web",
    image: "/project2.jpg",
    tech: [
      "/css-icon.svg",
      "/javascript-programming-language-icon.svg",
      "/tailwind-css-icon.svg",
      "/react-js-icon.svg",
      "/redux-icon.svg",
    ],
    tech2: [
      "css",
      "javascript",
      "tailwind css",
      "react",
      "redux",
      "python",
      "fast api",
      "github actions",
    ],
    description:
      "Built this project with a team of project managers, designers, frontend devs, backend devs, and devops during hng internship. Generate, edit and send love letters to your loved ones. I work at the frontend of this project. Right now, there are only 4 people managing it. We have over 1.5k users.",
  },
  {
    name: "E-shop",
    link: "https://deni-eshop.netlify.app/",
    git: "https://github.com/e-shop/",
    image: "/project14.png",
    tech: [
      "/sb.svg",
      "/jest-js-icon.svg",
      "/typescript-programming-language-icon.svg",
      "/styled-components-1.svg",
      "/nextjs-icon.svg",
    ],
    tech2: ["sass", "javascript", "react", "firebase"],
    description:
      "I needed to know more about react, took a course and we built this project together. Login and signup with firebase, add products to cart and other stuffs.",
  },
  {
    name: "AI",
    link: "https://radiant-choux-b539d0.netlify.app/",
    git: "https://github.com/",
    image: "/project13.png",
    tech2: ["tailwind css", "javascript", "react"],
    description:
      "More on tailwind and react. Tailwind makes building simple applications easier. I'm going to learn about AI in the future. But I have to learn more about python first.",
  },
  {
    name: "Quizzical",
    link: "https://juicio-quizzical.netlify.app",
    git: "https://github.com/juicio8/Quizzical",
    image: "/project1.jpg",
    description:
      "A scrimba solo project. Answer top quizzes and get score. I built this to learn more about React.",
    tech: [
      "/css-icon.svg",
      "/javascript-programming-language-icon.svg",
      "/react-js-icon.svg",
    ],
    tech2: ["css", "javascript", "react"],
  },
  {
    name: "WatchList",
    link: "https://watchlist-deni.netlify.app",
    git: "https://github.com/juicio8/Movie-WatchList",
    image: "/project3.jpg",
    description:
      "A Scrimba solo project. Select your favorite films and add it to your WatchList. I built this to learn more about javascript. It's impressive!!",
    tech: ["/css-icon.svg", "/javascript-programming-language-icon.svg"],
    tech2: ["css", "javascript"],
  },
  {
    name: "Lendsqr Test",
    link: "https://deni-wisdom-ochiche-lendsqr-fe-test.netlify.app",
    git: "https://github.com/juicio8/lendsqr-fe-test",
    image: "/project4.jpg",
    tech2: ["typescript", "sass", "vitetest", "react"],
    description:
      "A test to build a figma design. I passed but didn't really do well in the technical interview phase. I dive more into Software Enginnering because of this. It made me stronger ",
  },
  {
    name: "Metabnb",
    link: "https://lambent-khapse-f0075f.netlify.app",
    git: "https://github.com/juicio8/Metabnb",
    image: "/project5.jpg",
    description:
      "Built during my time as HNG intern. It was a test, to go to the next stage. I passed!",
    tech: [
      "/css-icon.svg",
      "/javascript-programming-language-icon.svg",
      "/react-js-icon.svg",
    ],
    tech2: ["css", "javascript", "react"],
  },
  {
    name: "Travel Journal",
    link: "https://magnificent-lokum-ace742.netlify.app",
    git: "",
    image: "/project6.jpg",
    description: "A Scrimba Solo Project.",
    tech: [
      "/css-icon.svg",
      "/javascript-programming-language-icon.svg",
      "/react-js-icon.svg",
    ],
    tech2: ["css", "javascript", "react"],
  },
  {
    name: "Metric Conversion",
    link: "https://reliable-speculoos-d172f8.netlify.app",
    git: "https://github.com/juicio8/Metric-converter",
    image: "/project7.jpg",
    description: "A Scrimba Solo Project",
    tech: ["/css-icon.svg", "/javascript-programming-language-icon.svg"],
    tech2: ["css", "javascript"],
  },
];
